### ISSUE TITLE
Zone/env deployment wizard

### ISSUE THREAD

**Issue by rhtyd** [shapeblue/primate#20]
Add a wizard or component for admins to deploy an environment

**Comment by anuragaw** [comment]
Update: Working on it and adding component like the image below:
https://user-images.githubusercontent.com/95203/62609115-c82c1380-b91e-11e9-8abf-7d9598cf060f.png

**Comment by iceteabottle** [comment]
@anuragaw I'm working on the vm wizard. Maybe hav a look at my PR https://github.com/shapeblue/primate/pull/35

**Comment by anuragaw** [comment]
@rhtyd - we are closing this?

**Comment by anuragaw** [comment]
Nevermind - I see we have a new ticket.
