### ISSUE TITLE
View dropdown should display project displayname, not project name

### ISSUE THREAD

**Issue by onitake** [shapeblue/primate#38]
The "View" dropdown in the top left corner displays a list of projects, just like the project dropdown in the legacy web UI did.

However, it's displaying internal project names and not each project's displayname.
Is there a particular reason for this design decision?

**Comment by svenvogel** [comment]
@onitake i think its tracked. i saw the same but at the moment its all work in progress so maybe not all things are there where it should it belongs. thanks for the info.
