### ISSUE TITLE
Catalan language has wrong flag

### ISSUE THREAD

**Issue by onitake** [shapeblue/primate#39]
The language selector displays the Canadian flag for Catalan language:
![image](https://user-images.githubusercontent.com/371687/64946262-bb320680-d872-11e9-9f14-a74698e45ad8.png)

Catalan has ISO 639-1 language code 'ca', which is distinct from ISO 3166 country code `ca`.
Perhaps thee should be a more complex mapping logic between language and icon file name.

**Comment by rhtyd** [comment]
@onitake what do you think is a more appropriate flag, or should we get rid of flags and stick to 2-3 letter codenames?

**Comment by DaanHoogland** [comment]
https://en.wikipedia.org/wiki/Senyera#/media/File:Flag_of_Catalonia.svg

**Comment by onitake** [comment]
@rhtyd It depends... Where did you obtain the existing flag icons?
Catalonia has it's own flag, as Daan already pointed out.

@DaanHoogland It's SVG - vector graphics can be scaled as appropriate. :wink:

**Comment by onitake** [comment]
Thanks!
