### ISSUE TITLE
Add actions on all views

### ISSUE THREAD

**Issue by rhtyd** [shapeblue/primate#40]
- [x] Cloud resources (instances, volumes, templates, isos etc.)
- [x] Business resources (users, accounts, domains, roles etc.)
- [x] Infra resources (zone, host, cluster, offerings, settings etc.) - @anuragaw

**Comment by rhtyd** [comment]
To be done:
- Migrate translations for action labels and also check for the form fields

**Comment by anuragaw** [comment]
PR - https://github.com/shapeblue/primate/pull/59

All translations, etc have been handled for forms and fields as well.
